sudo: false
language: cpp
gcc:
  - 4.8
  - 4.9
env:
  - SUITE=DGLM_TEST_ENABLE_CXX_98=ON
  - SUITE=DGLM_TEST_ENABLE_CXX_0X=ON

script: $CXX -v;mkdir ./build; cd ./build; cmake -DGLM_TEST_ENABLE=ON $SUITE ..; cmake --build .; ctest
