sudo: false
language: cpp
matrix:
  include:
    - os: linux
      compiler: g++-4.8


script: gcc -v;mkdir ./build; cd ./build; cmake -DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_CXX_98=ON ..; cmake --build .; ctest      
