sudo: false
language: cpp
compiler:
  - gcc-4.2
  - gcc-4.3
  - gcc-4.4
  - gcc-4.5
  - gcc-4.6
  - gcc-4.7
  - gcc-4.8
  - gcc-4.9
  - gcc-5.0
  - gcc-5.1
env:
  - SUITE=DGLM_TEST_ENABLE_CXX_98=ON
  - SUITE=DGLM_TEST_ENABLE_CXX_0X=ON

script: mkdir ./build; cd ./build; cmake -DGLM_TEST_ENABLE=ON $SUITE ..; cmake --build .; ctest
