os:
  - linux
  - osx

sudo:
  - false

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libstdc++-4.8-dev
      - gcc-4.8
      - libstdc++-4.7-dev
      - gcc-4.7

compiler:
  - gcc-4.7
  - gcc-4.8
env:
  - SUITE='DGLM_TEST_ENABLE_CXX_98=ON'
  - SUITE='DGLM_TEST_ENABLE_CXX_0X=ON'

script: gcc --version; mkdir ./build; cd ./build; cmake -DGLM_TEST_ENABLE=ON $SUITE ..; cmake --build .; ctest
